# Generated by Django 2.2.6 on 2019-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polis_ltd_sk', models.CharField(max_length=50)),
                ('polis_ltd_id', models.CharField(max_length=50)),
                ('polis_ltd_type', models.CharField(max_length=10)),
                ('polis_ltd_date_end', models.DateTimeField(verbose_name='Окончание срока действия')),
                ('polis_ltd_tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polis_ltd_outservice', models.CharField(max_length=200)),
                ('polis_ltd_inclusion', models.CharField(max_length=50)),
            ],
        ),
    ]
